### ISSUE TITLE
[A11y] aria menu

### ISSUE THREAD

**Issue by jolamar** [indiana-university/rivet-source#389] opened 2020-04-20 19:24 UTC
I think we're getting WAVE errors for dropdowns when we use them like navigation.. Here's what WAVE is saying

>ARIA menus are application menus (like those used in software menu) with a specific keyboard interactions. They are NOT for navigation links on a web site and must contain at least one menuitem, menuitemcheckbox, or menuitemradio element.

https://wave.webaim.org/report#/https://rivet.iu.edu/components/navigation/dropdown/

**Comment by scottanthonymurray** [comment] 2021-02-09 18:20
Closed as duplicate of #208

**Closed by scottanthonymurray** 2021-02-09 18:20 UTC
Labels: duplicate
